// 此文件由 tauri-specta 自动生成，请勿手动修改
// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * 初始化示例命令 - 用于验证 Tauri 命令机制
 */
async greet(name: string) : Promise<string> {
    return await TAURI_INVOKE("greet", { name });
},
/**
 * 获取应用配置
 */
async getConfig() : Promise<Result<AppConfig, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 保存应用配置
 */
async setConfig(config: AppConfig) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_config", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 创建新的 Session
 */
async createSession(modeId: string, name: string | null, audioConfig: SessionAudioConfig | null) : Promise<Result<SessionMeta, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_session", { modeId, name, audioConfig }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 获取 Session 元数据
 */
async getSession(sessionId: string) : Promise<Result<SessionMeta, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_session", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 列出历史 Session
 */
async listSessions(limit: number | null, offset: number | null) : Promise<Result<SessionRecord[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_sessions", { limit, offset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 删除 Session
 */
async deleteSession(sessionId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_session", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 获取 Session 转录内容
 */
async getTranscript(sessionId: string) : Promise<Result<TranscriptSegment[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_transcript", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 检查指定权限状态
 */
async checkPermission(permission: PermissionType) : Promise<PermissionStatus> {
    return await TAURI_INVOKE("check_permission", { permission });
},
/**
 * 请求指定权限
 * 
 * 注意：并非所有权限都可以程序化请求
 * - macOS 屏幕录制和辅助功能需要在系统设置中手动授权
 * - 麦克风权限可以通过弹窗请求
 */
async requestPermission(permission: PermissionType) : Promise<PermissionStatus> {
    return await TAURI_INVOKE("request_permission", { permission });
},
/**
 * 打开系统权限设置页面
 */
async openPermissionSettings(permission: PermissionType) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_permission_settings", { permission }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 检查所有权限状态
 */
async checkAllPermissions() : Promise<AllPermissionsStatus> {
    return await TAURI_INVOKE("check_all_permissions");
},
/**
 * 检查所有必需权限是否已授权
 */
async allRequiredPermissionsGranted() : Promise<boolean> {
    return await TAURI_INVOKE("all_required_permissions_granted");
},
/**
 * 列出所有可用的音频源
 * 
 * 返回系统音频源和麦克风设备列表
 */
async listAudioSources() : Promise<Result<AudioSource[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_audio_sources") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 列出可用的麦克风设备
 */
async listMicrophones() : Promise<Result<AudioSource[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_microphones") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 列出可用的系统音频源（macOS）
 * 
 * 包括系统音频和正在播放音频的应用
 */
async listSystemAudioSources() : Promise<Result<AudioSource[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_system_audio_sources") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * AI 配置
 */
export type AiConfig = { 
/**
 * AI 提供商
 */
provider: AiProvider; 
/**
 * `OpenAI` 配置
 */
openai: OpenAiConfig | null; 
/**
 * Claude 配置
 */
claude: ClaudeConfig | null; 
/**
 * Ollama 配置
 */
ollama: OllamaConfig | null }
/**
 * AI 提供商
 */
export type AiProvider = "none" | "openai" | "claude" | "ollama"
/**
 * 所有权限的状态汇总
 */
export type AllPermissionsStatus = { 
/**
 * 系统音频录制权限状态
 */
systemAudioRecording: PermissionStatus; 
/**
 * 麦克风权限状态
 */
microphone: PermissionStatus; 
/**
 * 辅助功能权限状态
 */
accessibility: PermissionStatus; 
/**
 * 是否所有必需权限都已授权
 */
allRequiredGranted: boolean }
/**
 * 应用全局配置
 */
export type AppConfig = { 
/**
 * Schema 版本号
 */
version: number; 
/**
 * 通用配置
 */
general: GeneralConfig; 
/**
 * 音频配置
 */
audio: AudioConfig; 
/**
 * ASR 配置
 */
asr: AsrConfig; 
/**
 * AI 配置
 */
ai: AiConfig; 
/**
 * 快捷键配置
 */
hotkeys: HotkeyConfig; 
/**
 * 存储配置
 */
storage: StorageConfig }
/**
 * ASR 配置
 */
export type AsrConfig = { 
/**
 * 模型 ID
 */
modelId?: string; 
/**
 * 识别语言
 */
language?: AsrLanguage; 
/**
 * 启用标点
 */
enablePunctuation?: boolean; 
/**
 * VAD 灵敏度
 */
vadSensitivity?: number }
/**
 * ASR 语言
 */
export type AsrLanguage = "auto" | "zh" | "en"
/**
 * 音频配置
 */
export type AudioConfig = { 
/**
 * 默认系统音频源 ID
 */
defaultSystemSource: string | null; 
/**
 * 默认麦克风 ID
 */
defaultMicrophone: string | null; 
/**
 * 采样率
 */
sampleRate?: number; 
/**
 * 声道数
 */
channels?: number; 
/**
 * 输入增益
 */
inputGain?: number }
/**
 * 音频源信息
 */
export type AudioSource = { 
/**
 * 音频源唯一标识
 */
id: string; 
/**
 * 音频源名称（用于显示）
 */
name: string; 
/**
 * 音频源类型
 */
source_type: AudioSourceType; 
/**
 * 是否为默认设备
 */
is_default: boolean; 
/**
 * 采样率（Hz）
 */
sample_rate?: number | null; 
/**
 * 通道数
 */
channels?: number | null }
/**
 * 音频源信息
 */
export type AudioSourceInfo = { 
/**
 * 设备 ID
 */
id: string; 
/**
 * 类型
 */
type: AudioSourceType; 
/**
 * 名称
 */
name: string; 
/**
 * 应用 Bundle ID
 */
bundleId?: string | null }
/**
 * 音频源类型
 */
export type AudioSourceType = 
/**
 * 系统音频（全局）
 */
{ type: "system_audio" } | 
/**
 * 指定应用的音频
 */
{ type: "application"; bundle_id: string; pid: number } | 
/**
 * 麦克风输入
 */
{ type: "microphone" }
/**
 * 音频源类型
 */
export type AudioSourceType = 
/**
 * 系统音频
 */
"system" | 
/**
 * 应用音频
 */
"application" | 
/**
 * 麦克风
 */
"microphone"
/**
 * Claude 配置
 */
export type ClaudeConfig = { 
/**
 * API Key
 */
apiKey?: string; 
/**
 * API 基础 URL
 */
baseUrl?: string; 
/**
 * 模型名称
 */
model?: string; 
/**
 * 温度参数
 */
temperature?: number; 
/**
 * 最大 Token 数
 */
maxTokens?: number }
/**
 * 通用配置
 */
export type GeneralConfig = { 
/**
 * 界面语言
 */
language: Language; 
/**
 * 主题模式
 */
theme: Theme; 
/**
 * 开机启动
 */
launchAtStartup?: boolean; 
/**
 * macOS 菜单栏图标
 */
showInMenubar?: boolean; 
/**
 * Windows 托盘图标
 */
showInTray?: boolean; 
/**
 * 最小化到托盘
 */
minimizeToTray?: boolean }
/**
 * 快捷键配置
 */
export type HotkeyConfig = { 
/**
 * 输入法模式切换
 */
inputMethodToggle?: string; 
/**
 * 开始/停止录制
 */
startStopRecording?: string; 
/**
 * 暂停/恢复
 */
pauseResume?: string }
/**
 * 界面语言
 */
export type Language = "zh-cn" | "en-us"
/**
 * Ollama 配置
 */
export type OllamaConfig = { 
/**
 * API 基础 URL
 */
baseUrl?: string; 
/**
 * 模型名称
 */
model?: string; 
/**
 * 温度参数
 */
temperature?: number }
/**
 * `OpenAI` 配置
 */
export type OpenAiConfig = { 
/**
 * API Key（加密存储）
 */
apiKey?: string; 
/**
 * API 基础 URL
 */
baseUrl?: string; 
/**
 * 模型名称
 */
model?: string; 
/**
 * 温度参数
 */
temperature?: number; 
/**
 * 最大 Token 数
 */
maxTokens?: number }
/**
 * 权限状态枚举
 */
export type PermissionStatus = 
/**
 * 已授权
 */
"granted" | 
/**
 * 已拒绝
 */
"denied" | 
/**
 * 未决定（首次请求前）
 */
"notDetermined" | 
/**
 * 受限（如家长控制）
 */
"restricted" | 
/**
 * 不适用（如 Windows 不需要屏幕录制权限）
 */
"notApplicable"
/**
 * 权限类型枚举
 * 
 * 定义应用所需的各种系统权限
 */
export type PermissionType = 
/**
 * 系统音频录制权限（macOS 14.4+ 支持仅音频录制）
 * - macOS: 需要在系统设置 > 隐私与安全性 > 录屏与系统录音 中授权
 * 用户可选择"仅录音"而不需要屏幕录制权限
 * - Windows: 不需要（NotApplicable）
 */
"systemAudioRecording" | 
/**
 * 麦克风权限
 * - macOS: 可通过弹窗请求
 * - Windows: 可通过弹窗请求
 */
"microphone" | 
/**
 * 辅助功能权限（用于全局快捷键和输入法模式）
 * - macOS: 需要在系统偏好设置中授权
 * - Windows: 不需要（NotApplicable）
 */
"accessibility"
/**
 * Session 音频配置
 */
export type SessionAudioConfig = { 
/**
 * 音频源列表
 */
sources: AudioSourceInfo[]; 
/**
 * 采样率
 */
sampleRate: number; 
/**
 * 声道数
 */
channels: number; 
/**
 * 是否保存音频
 */
saveAudio: boolean }
/**
 * Session 元数据
 */
export type SessionMeta = { 
/**
 * Session ID
 */
id: string; 
/**
 * Schema 版本
 */
version: number; 
/**
 * 用户自定义名称
 */
name?: string | null; 
/**
 * 所属模式 ID
 */
modeId: string; 
/**
 * 创建时间（ISO 8601）
 */
createdAt: string; 
/**
 * 更新时间（ISO 8601）
 */
updatedAt: string; 
/**
 * 完成时间（ISO 8601）
 */
completedAt?: string | null; 
/**
 * 状态
 */
status: SessionStatus; 
/**
 * 错误信息
 */
error?: string | null; 
/**
 * 音频配置
 */
audioConfig: SessionAudioConfig; 
/**
 * 统计信息
 */
stats?: SessionStats; 
/**
 * 用户标签
 */
tags?: string[] }
/**
 * 数据库中的 Session 记录
 */
export type SessionRecord = { id: string; modeId: string; name: string | null; status: string; createdAt: string; updatedAt: string; completedAt: string | null; durationMs: number; wordCount: number; characterCount: number; directoryPath: string; tags: string | null }
/**
 * Session 统计信息
 */
export type SessionStats = { 
/**
 * 总时长（毫秒）
 */
durationMs?: number; 
/**
 * 音频时长（毫秒）
 */
audioDurationMs?: number; 
/**
 * 转录段落数
 */
segmentCount?: number; 
/**
 * 总字数
 */
wordCount?: number; 
/**
 * 总字符数
 */
characterCount?: number }
/**
 * Session 状态
 */
export type SessionStatus = 
/**
 * 已创建
 */
"created" | 
/**
 * 录制中
 */
"recording" | 
/**
 * 已暂停
 */
"paused" | 
/**
 * 已完成
 */
"completed" | 
/**
 * 错误
 */
"error"
/**
 * 存储配置
 */
export type StorageConfig = { 
/**
 * 自定义存储路径
 */
basePath: string | null; 
/**
 * 默认保存音频
 */
saveAudioByDefault?: boolean; 
/**
 * 启用自动清理
 */
autoCleanupEnabled?: boolean; 
/**
 * 清理天数
 */
cleanupAfterDays?: number; 
/**
 * 最大存储空间 (GB)
 */
maxStorageSizeGb?: number }
/**
 * 主题模式
 */
export type Theme = "light" | "dark" | "system"
/**
 * 转录分段
 */
export type TranscriptSegment = { 
/**
 * 分段 ID
 */
id: string; 
/**
 * 开始时间（秒）
 */
startTime: number; 
/**
 * 结束时间（秒）
 */
endTime: number; 
/**
 * 转录文本
 */
text: string; 
/**
 * 是否为最终结果
 */
isFinal: boolean; 
/**
 * 置信度
 */
confidence?: number | null; 
/**
 * 音频来源
 */
source?: TranscriptSource | null; 
/**
 * 检测到的语言
 */
language?: string | null; 
/**
 * 词级时间戳
 */
words?: WordTimestamp[] | null; 
/**
 * 创建时间（ISO 8601）
 */
createdAt: string }
/**
 * 转录来源
 */
export type TranscriptSource = 
/**
 * 系统音频
 */
"system" | 
/**
 * 麦克风
 */
"microphone" | 
/**
 * 混合
 */
"mixed"
/**
 * 词级时间戳
 */
export type WordTimestamp = { 
/**
 * 词
 */
word: string; 
/**
 * 开始时间
 */
start: number; 
/**
 * 结束时间
 */
end: number; 
/**
 * 置信度
 */
confidence?: number | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
